const projectData = [
  {
    img: ['/reactLogo.png'],
    title: 'Portfolio',
    category: 'JavaScript',
    details: 'You\'re here!',
    url: 'https://github.com/m1dunfee/Portfolio3',
  },
  {
    img: ['/pythonLogo.png'],
    title: 'Pathfindre AI',
    category: 'Python',
    details: 'Using Reinforcement Learning and Neural Networks, I implement the q-learning algorithm to solve a pathfinding problem.',
    url: 'https://github.com/m1dunfee/cs-370-ml-pathfinder',
  }, 
  {
    img: ['/pythonLogo.png'],
    title: 'Game AI',
    category: 'Python',
    details: 'Checkers AI with minimax & alpha-beta pruning; reflections on design trade-offs & future work. Includes inference system and original implementions.',
    url: 'https://github.com/m1dunfee/Game-AI-Checkers',
  }, 
  {
    img: ['/MEAN.png'],
    title: 'Mean fullstack',
    category: 'MEAN',
    details: 'This repo includes a Express server, API, and admin app. It host two sites on ports 3000 and 4200, using Mongodb, Express, Angular, and Node.js.',
    url: 'https://github.com/m1dunfee/cs465-fullstack-MEAN',
  },   
  {
    img: ['/cpp_logo.png'],
    title: 'Big\'O',
    category: 'C++',
    details: 'This is the final project with reflections. Preliminary projects on my github labeled "cs300" + "dataStructure"',
    url: 'https://github.com/m1dunfee/cs300Final',
  },  
  {
    img: ['/javaLogo.webp'],
    title: 'jUnit',
    category: 'Java',
    details: 'Example of using a testing libraries to anotate and build custom test cases.',
    url: 'https://github.com/m1dunfee/cs320jUnit',
  },  
    {
    img: ['/pythonLogo.png'],
    title: 'Data Visualization',
    category: 'Python',
    details: 'Using mongodb and python to build an interactive system.',
    url: 'https://github.com/m1dunfee/cs340ClientServer',
  },
    {
    img: ['/cpp_logo.png'],
    title: 'OpenGL retro game',
    category: 'Python',
    details: 'Retro style game with custom controls and graphics.',
    url: 'https://github.com/m1dunfee/cs330-opengl-game',
  },
    {
    img: ['/cpp_logo.png'],
    title: '3D graphics and visualization with OpenGL',
    category: 'C++',
    details: 'I use openGL to create a 3d scene of a coffeeshop table with custom graphics, navigation and lighting.',
    url: 'https://github.com/m1dunfee/cs330-graphics-and-visualization',
  },
  {
    img: ['/matLab.png'],
    title: 'Image Compression',
    category: 'MatLab',
    details: 'Using linear algebra to compress the pixel matrix by projecting onto pivot points, thereby reducing the matrix\'s dimensionality without compromising image clarity.',
    url: 'https://github.com/m1dunfee/ImageCompression',
  },
  {
    img: ['/javaLogo.webp', '/CISA_Logo.png', '/OWASP.png'],
    title: 'Security Audit',
    category: 'Java',
    details: 'OWASP Security Audit and CISA analysis',
    url: 'https://github.com/m1dunfee/JavaSecurityAudit',
  },
  {
    img: ['/javaLogo.webp'],
    title: 'LetsEncrypt',
    category: 'Java',
    details: 'Certificate Authorities and Encryption',
    url: 'https://github.com/m1dunfee/LetsEncrypt',
  },
  {
    img: ['/cpp_logo.png'],
    title: 'RSA Encryption',
    category: 'C++',
    details: 'The math behind RSA',
    url: 'https://github.com/m1dunfee/RSA-Encryption',
  },
  {
    img: ['/pythonLogo.png'],
    title: 'Prismatica',
    category: 'Python',
    details: 'LLM / IoT project.',
    url: 'https://github.com/m1dunfee/Prismatica',
  },
  {
    img: ['/reactLogo.png', '/Nucamp.png'],
    title: 'Nucamp',
    category: 'React',
    details: 'Demo site used for teaching React.',
    url: 'https://github.com/m1dunfee/Nucamp-react-demo-site',
  },
  {
    img: ['/reactLogo.png'],
    title: 'Multiversal',
    category: 'React',
    details: 'Just a fun landing page to a discord server',
    url: 'https://github.com/m1dunfee/Multiversal-space',
  },
  {
    img: ['/reactLogo.png'],
    title: 'Originally Yours Upholstery',
    category: 'React',
    details: 'Business Site',
    url: 'https://github.com/m1dunfee/originallyyoursupholstery',
  },
];

export default projectData;


